export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export {default as Hero} from "./Hero"
export {default as Main} from "./Main"
export { default as DestinationHero} from "./destinationsHero"
export {default as Cards } from "./Cards"